name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Authorize Docker push
        run: gcloud auth configure-docker

      - name: Build and Push Container
        run: |-
          docker build -t gcr.io/${{ secrets.GCP_PROJECT }}/black-global-lens:${{ github.sha }} .
          docker push gcr.io/${{ secrets.GCP_PROJECT }}/black-global-lens:${{ github.sha }}

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: black-global-lens
          image: gcr.io/${{ secrets.GCP_PROJECT }}/black-global-lens:${{ github.sha }}
          region: us-central1
          env_vars: |
            NODE_ENV=production
